#############################################################################
# Makefile for building: Parser
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  Parser.pro
# Template: subdirs
# Command: C:\Qt\5.10.0\msvc2015\bin\qmake.exe -o Makefile Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.10.0\msvc2015\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.10.0\msvc2015\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.10.0\msvc2015\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-libs-QGumboParser-QGumboParser \
		sub-Parser


sub-libs-QGumboParser-QGumboParser-qmake_all:  FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	cd libs\QGumboParser\QGumboParser\ && $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && $(MAKE) -f Makefile qmake_all
sub-libs-QGumboParser-QGumboParser: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-libs-QGumboParser-QGumboParser-make_first-ordered: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-libs-QGumboParser-QGumboParser-make_first: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-libs-QGumboParser-QGumboParser-all-ordered: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-libs-QGumboParser-QGumboParser-all: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-libs-QGumboParser-QGumboParser-clean-ordered: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-libs-QGumboParser-QGumboParser-clean: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-libs-QGumboParser-QGumboParser-distclean-ordered: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-libs-QGumboParser-QGumboParser-distclean: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-libs-QGumboParser-QGumboParser-install_subtargets-ordered: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-libs-QGumboParser-QGumboParser-install_subtargets: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-libs-QGumboParser-QGumboParser-uninstall_subtargets-ordered: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-libs-QGumboParser-QGumboParser-uninstall_subtargets: FORCE
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Parser-qmake_all: sub-libs-QGumboParser-QGumboParser-qmake_all FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	cd Parser\ && $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && $(MAKE) -f Makefile qmake_all
sub-Parser: FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Parser-make_first-ordered: sub-libs-QGumboParser-QGumboParser-make_first-ordered  FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Parser-make_first: FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Parser-all-ordered: sub-libs-QGumboParser-QGumboParser-all-ordered  FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Parser-all: FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Parser-clean-ordered: sub-libs-QGumboParser-QGumboParser-clean-ordered  FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Parser-clean: FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Parser-distclean-ordered: sub-libs-QGumboParser-QGumboParser-distclean-ordered  FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Parser-distclean: FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Parser-install_subtargets-ordered: sub-libs-QGumboParser-QGumboParser-install_subtargets-ordered  FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Parser-install_subtargets: FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Parser-uninstall_subtargets-ordered: sub-libs-QGumboParser-QGumboParser-uninstall_subtargets-ordered  FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Parser-uninstall_subtargets: FORCE
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: Parser.pro ..\..\Qt\5.10.0\msvc2015\mkspecs\win32-msvc\qmake.conf ..\..\Qt\5.10.0\msvc2015\mkspecs\features\spec_pre.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\common\angle.conf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\common\windows-vulkan.conf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\common\msvc-desktop.conf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\qconfig.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3drender.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axbase.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axserver.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_charts.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_core.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_core_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_dbus.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_designer.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_edid_support_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_gui.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_help.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_help_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_location.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_location_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_network.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_network_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_nfc.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_opengl.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_positioning.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_purchasing.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qml.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quick.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_repparser.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_script.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_script_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_scxml.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_sensors.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_serialport.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_sql.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_svg.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_testlib.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_uitools.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webengine.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webengine_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_websockets.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webview.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_widgets.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_winextras.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_xml.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\qt_functions.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\qt_config.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\win32-msvc\qmake.conf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\spec_post.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\exclusive_builds.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\common\msvc-version.conf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\toolchain.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\default_pre.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\win32\default_pre.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\resolve_config.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\exclusive_builds_post.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\default_post.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\qml_debug.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\precompile_header.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\warn_on.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\qmake_use.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\file_copies.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\win32\windows.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\testcase_targets.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\exceptions.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\yacc.prf \
		..\..\Qt\5.10.0\msvc2015\mkspecs\features\lex.prf \
		Parser.pro
	$(QMAKE) -o Makefile Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
..\..\Qt\5.10.0\msvc2015\mkspecs\features\spec_pre.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\common\angle.conf:
..\..\Qt\5.10.0\msvc2015\mkspecs\common\windows-vulkan.conf:
..\..\Qt\5.10.0\msvc2015\mkspecs\common\msvc-desktop.conf:
..\..\Qt\5.10.0\msvc2015\mkspecs\qconfig.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3danimation.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dcore.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dextras.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dinput.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquick.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3drender.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axbase.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axserver.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_charts.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_charts_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_core.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_core_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_dbus.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_designer.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_designer_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_edid_support_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_gamepad.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_gui.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_gui_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_help.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_help_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_location.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_location_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_network.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_network_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_networkauth.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_nfc.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_opengl.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_positioning.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_purchasing.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_purchasing_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qml.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qml_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quick.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quick_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_repparser.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_script.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_script_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_scripttools.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_scxml.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_sensors.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_serialbus.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_serialport.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_sql.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_sql_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_svg.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_svg_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_testlib.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_uitools.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_vulkan_support_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webchannel.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webengine.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webengine_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_websockets.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webview.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_webview_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_widgets.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_winextras.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_xml.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_xml_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\qt_functions.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\qt_config.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\win32-msvc\qmake.conf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\spec_post.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\exclusive_builds.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\common\msvc-version.conf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\toolchain.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\default_pre.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\win32\default_pre.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\resolve_config.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\exclusive_builds_post.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\default_post.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\qml_debug.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\precompile_header.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\warn_on.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\qmake_use.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\file_copies.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\win32\windows.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\testcase_targets.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\exceptions.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\yacc.prf:
..\..\Qt\5.10.0\msvc2015\mkspecs\features\lex.prf:
Parser.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-libs-QGumboParser-QGumboParser-qmake_all sub-Parser-qmake_all FORCE

make_first: sub-libs-QGumboParser-QGumboParser-make_first-ordered sub-Parser-make_first-ordered  FORCE
all: sub-libs-QGumboParser-QGumboParser-all-ordered sub-Parser-all-ordered  FORCE
clean: sub-libs-QGumboParser-QGumboParser-clean-ordered sub-Parser-clean-ordered  FORCE
distclean: sub-libs-QGumboParser-QGumboParser-distclean-ordered sub-Parser-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-libs-QGumboParser-QGumboParser-install_subtargets-ordered sub-Parser-install_subtargets-ordered FORCE
uninstall_subtargets: sub-libs-QGumboParser-QGumboParser-uninstall_subtargets-ordered sub-Parser-uninstall_subtargets-ordered FORCE

sub-libs-QGumboParser-QGumboParser-debug_ordered:
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Parser-debug_ordered: sub-libs-QGumboParser-QGumboParser-debug_ordered 
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-libs-QGumboParser-QGumboParser-debug_ordered sub-Parser-debug_ordered

sub-libs-QGumboParser-QGumboParser-release_ordered:
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Parser-release_ordered: sub-libs-QGumboParser-QGumboParser-release_ordered 
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-libs-QGumboParser-QGumboParser-release_ordered sub-Parser-release_ordered

sub-libs-QGumboParser-QGumboParser-check_ordered:
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Parser-check_ordered: sub-libs-QGumboParser-QGumboParser-check_ordered 
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-libs-QGumboParser-QGumboParser-check_ordered sub-Parser-check_ordered

sub-libs-QGumboParser-QGumboParser-benchmark_ordered:
	@if not exist libs\QGumboParser\QGumboParser\ mkdir libs\QGumboParser\QGumboParser\ & if not exist libs\QGumboParser\QGumboParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\QGumboParser\QGumboParser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\libs\QGumboParser\QGumboParser\QGumboParser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Parser-benchmark_ordered: sub-libs-QGumboParser-QGumboParser-benchmark_ordered 
	@if not exist Parser\ mkdir Parser\ & if not exist Parser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Parser\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\QtProjectWin\Parser\Parser\Parser.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-libs-QGumboParser-QGumboParser-benchmark_ordered sub-Parser-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

